### PR TITLE
Change source domain to module.oooh.io

### PR DESCRIPTION
**Pull request by allan-o3h**

### CODE REVIEW

**Comment by roger-o3h** [comment]
You even thought to bump the version number! Thank you! I'm just gonna sit on this until http://module.oooh.io/api/o3h.js resolves though.

**Comment by roger-o3h** [comment]
Oh, looks like https: resolves while http: does not. Is https going to be required? That might necessitate more changes.

**Comment by allan-o3h** [comment]
> Oh, looks like https: resolves while http: does not. Is https going to be required? That might necessitate more changes.

That was kind of arbitrary, is redirecting to https okay? otherwise I'll just allow http on the cdn as well.

**Comment by roger-o3h** [comment]
> > Oh, looks like https: resolves while http: does not. Is https going to be required? That might necessitate more changes.
> 
> That was kind of arbitrary, is redirecting to https okay? otherwise I'll just allow http on the cdn as well.

Hmm, I'd have to rack my brain for a minute to try to imagine what might break... maybe it's a good idea to go ahead and do this and see what breaks, since we're not turning off the old domain yet?

**Comment by allan-o3h** [comment]
> > > Oh, looks like https: resolves while http: does not. Is https going to be required? That might necessitate more changes.
> > 
> > 
> > That was kind of arbitrary, is redirecting to https okay? otherwise I'll just allow http on the cdn as well.
> 
> Hmm, I'd have to rack my brain for a minute to try to imagine what might break... maybe it's a good idea to go ahead and do this and see what breaks, since we're not turning off the old domain yet?

Good call out, made some changes to how we proxy and it seems to work properly now with ssl.

**Review by roger-o3h — APPROVED** [review]
Nice, looks like it's working fine this way, I guess modules will have no idea since the proxy is totally opaque to them. 💯

**Pull request merged**
